- lib/hashdiff/lcs.rb
These vars were already created at line 13 but they weren't used before.
This also fixes warnings when running script which uses hashdiff with ruby warnings turned on.
> Use a_start and b_start variables in HashDiff.lcs

- README.md
- lib/hashdiff/util.rb
- spec/hashdiff/diff_spec.rb
- spec/hashdiff/util_spec.rb
This allows for easy string comparisons where you don't care about case.
Resolves #13
> Add :case_insensitive option

- lib/hashdiff/util.rb
- spec/hashdiff/patch_spec.rb
A hash key with anything not matching \w (word characters) like -|, etc
would not match the regex detecting arrays in the patch path and would
not patch correctly.
> Fix bug with array under hash key with non-word characters.

- .travis.yml
- Gemfile
- lib/hashdiff/diff.rb
- lib/hashdiff/patch.rb
- Add 2.2, 2.3 and 2.4 to Travis CI.
- Modern version of `rake` fails with old RSpec so its version should be restricted.
- Fixnum is deprecated in Ruby 2.4.0 so replace it with Integer.
> New rubies support.

- lib/hashdiff/util.rb
HashDiff#similar? compares values based on "node count" using
HashDiff#count_nodes and HashDiff#diff (if the counts don't cancel out). If
`a` and `b` are arrays/hashes `count_nodes` recursively counts the elements,
otherwise returns 1. If `a` and `b` are not arrays/hashes, HashDiff#similar?
needlessly counts/diffs values that will ultimately end up passing
through HashDiff#compare_values.
A considerable performance improvement can be had by circumventing the
needless recursion and call HashDiff#compare_values if `a` and `b` are
not arrays/hashes.
This has been benchmarked with this snippet:
```ruby
$LOAD_PATH << File.join(File.dirname(__FILE__), 'lib')
require 'hashdiff'
require 'benchmark'
seq1 = %w(a b c e h j l m n p)
seq2 = %w(a b c d e f j k l m r s t)
n = 10000
Benchmark.bm do |x| …
```
> Greatly improve performance of HashDiff#similar?

- README.md
- lib/hashdiff/diff.rb
- lib/hashdiff/lcs.rb
- lib/hashdiff/patch.rb
- lib/hashdiff/util.rb
- spec/hashdiff/best_diff_spec.rb
- spec/hashdiff/diff_spec.rb
- spec/hashdiff/patch_spec.rb
Hello :wave:, thanks for your work on this gem. We've found it useful.
This PR introduces an array_path option that can be used when generating a diff. This represents the path to aspects of the diff as an array rather than a string.
eg.
```
x = {'a' => 1}
y = {'a' => 2}
HashDiff.diff(x, y)
=> [["~", "a", 1, 2]]h
HashDiff.diff(x, y, :array_path => true)
=> [["~", ["a"], 1, 2]]
```
This allows there to be more flexibility with the types used as keys in a hash. Allowing workarounds for issues such as: https://github.com/liufengyun/hashdiff/issues/25
eg
```
x = {'a'=>1}
y = {:a=>1}
HashDiff.diff(x, y)
=> [["-", "a", 1], ["+", "a", 1]]
HashDiff.diff(x, y, :array_path => true)
=> [["-", ["a"], 1], ["+", [:a], 1]]
```
And improved ability to patch hashes with keys:
eg
```
x = {a: {b: :c}}
y = …
```
> Introduce an array_path option

- lib/hashdiff.rb
- lib/hashdiff/diff.rb
- lib/hashdiff/linear_compare_array.rb
- spec/hashdiff/diff_array_spec.rb
- spec/hashdiff/diff_spec.rb
- spec/hashdiff/linear_compare_array_spec.rb
Hello again :wave:
We hit some problems using HashDiff in a web application at request time. We noticed the problem occurred when we were comparing arrays with lots of items in (909 length array with each item a hash) and noticed our request times spiking.
We traced this issue back to the approach used to work out the longest common subsequence. This PR introduces the ability to disable the LCS algorithm for a simpler one that runs at a linear complexity.
The LCS algorithm produces excellent diffs. Unfortunately it has a n<sup>2</sup> complexity which can lead to extremely slow computations on large arrays.
```
> require 'hashdiff';require 'benchmark'
> x = (1..100).map { |i| { key: i, foo: :bar } }
> puts Benchmark.measure { HashDiff.diff(x, x) }
0.420000   0.000000   0.420000 ( …
```
> Option to allow array comparisons in linear complexity

- .travis.yml
- hashdiff.gemspec
As noted on #38, commit a885a778b1afb9694f15939763cb1fd3d461ce2d includes code that will not work with ruby-1.8.7.  Updated the gemspec to reflect this so it doesn't get forgotten.
> update minimum ruby to reflect actual support

- lib/hashdiff/diff.rb
- lib/hashdiff/lcs.rb
- lib/hashdiff/util.rb
- spec/hash_diff/util_spec.rb
It should be a little bit faster (or a lot faster in some cases) and use less memory.
> Performance and memory fixes

- hashdiff.gemspec
This adds direct links on the rubygems website. It also helps with automated management of updates.
> Add rubygems links

- README.md
- changelog.md
- hashdiff.gemspec
- lib/hashdiff.rb
- lib/hashdiff/compare_hashes.rb
- lib/hashdiff/diff.rb
- lib/hashdiff/lcs.rb
- lib/hashdiff/lcs_compare_arrays.rb
- lib/hashdiff/linear_compare_array.rb
- lib/hashdiff/patch.rb
- lib/hashdiff/util.rb
- lib/hashdiff/version.rb
- spec/hashdiff/best_diff_spec.rb
- spec/hashdiff/diff_array_spec.rb
- spec/hashdiff/diff_spec.rb
- spec/hashdiff/lcs_spec.rb
- spec/hashdiff/linear_compare_array_spec.rb
- spec/hashdiff/patch_spec.rb
- spec/hashdiff/util_spec.rb
Why This Change Is Necessary
========================================================================
The name of this gem is `hashdiff`. There is another gem named
`hash_diff`. When they are both required via dependencies, errors are
thrown. Additionally since the behavior is different, gems that are
relying on `hashdiff`'s behavior, may get `hash_diff`'s behavior and
vice versa.
The reason for the conflict is because, based on ruby conventions, _'s
are the separators for camel case.
So:
```ruby
'hashdiff'.camelize # => "Hashdiff"
'hash_diff'.camelize # => "HashDiff"
```
Unfortunately instead of making the base module of this gem `Hashdiff`,
it's called `HashDiff` and it conflicts.
How These Changes Address the Issue
======================================================================== …
> Change HashDiff Constant to Hashdiff

- hashdiff.gemspec
- lib/hashdiff.rb
- lib/hashdiff/version.rb
This PR will allow users who are annoyed by the deprecation warnings and/or those who have updated their code to reflect the constant change to manually specify the beta version in their `Gemfile` and remove them.
Like so:
```ruby
gem 'hashdiff', ['>= 1.0.0.beta1', '< 2.0.0']
```
> Release 1.0.0.beta1 With Deprecation Warnings and Shim Removed

- README.md
Follow up #27 and #28.
Ruby 2.4.0 unifies Fixnum and Bignum into Integer.
This PR updates Fixnum to Integer in README.md.
> Update Fixnum to Integer in README.md

- lib/hashdiff/version.rb
This PR fixes the following RuboCop offense when using Ruby 2.2 or lower.
```console
% bundle exec rake
(snip)
Running RuboCop...
Inspecting 20 files
.............C......
Offenses:
lib/hashdiff/version.rb:4:13: C: Style/MutableConstant: Freeze mutable
objects assigned to constants.
VERSION = '1.0.0.beta1'
^^^^^^^^^^^^^
20 files inspected, 1 offense detected
RuboCop failed!
```
https://travis-ci.org/liufengyun/hashdiff/builds/546282876
This is a regression by https://github.com/liufengyun/hashdiff/pull/70.
> Fix a RuboCop offense

- lib/hashdiff/util.rb
This fixes the failing build (e.g. https://travis-ci.org/liufengyun/hashdiff/builds/558766332)
> Fix rubocop Style/FloatDivision violation

- lib/hashdiff/util.rb
- spec/hashdiff/util_spec.rb
This fixes an issue where `comparable?(x, y)` != `comparable?(y, x)`, when x is an instance of a subclass of `Hash` (or `Array`), and y is an instance of `Hash` (or `Array`) directly.
Resolves https://github.com/liufengyun/hashdiff/issues/54
> Make comparable? commutative

- .rubocop.yml
- README.md
- hashdiff.gemspec
- spec/hashdiff/readme_spec.rb
- spec/hashdiff/util_spec.rb
```
>> Hashdiff.diff([1], [2], :comparison => { :numeric_tolerance => 0.1, :strip => true })
NoMethodError (undefined method `call' for {:numeric_tolerance=>0.1, :strip=>true}:Hash)
```
... also modernize the readme and make sure it stays valid
> fix invalid readme examples

- README.md
- changelog.md
- lib/hashdiff/compare_hashes.rb
- lib/hashdiff/diff.rb
- lib/hashdiff/version.rb
- spec/hashdiff/diff_spec.rb
Added an option :indifferent to allow ignoring differences between strings and symbols as keys. This behaves similarly to the Rails/ActiveSupport Hash#with_indifferent_access modifier.
Included a spec and documentation.
> Add :indifferent option

- .rubocop.yml
- Gemfile
- README.md
- changelog.md
- hashdiff.gemspec
- lib/hashdiff/compare_hashes.rb
- lib/hashdiff/diff.rb
- spec/hashdiff/diff_spec.rb
So here is a PR. I've had to update some gem deps to get tests to run with Ruby 3.2/3.3, hope this is OK:
Looks like `gem 'rake', '< 11'` was pinned in the Gemfile because of a [change in RSpec](https://stackoverflow.com/questions/35893584/nomethoderror-undefined-method-last-comment-after-upgrading-to-rake-11). However, Ruby 3.2+ needs a [more recent Rake](https://github.com/ruby/rake/issues/431) - so I've bumped RSpec dep to `~> 3.5` as [this comment](https://stackoverflow.com/questions/35893584/nomethoderror-undefined-method-last-comment-after-upgrading-to-rake-11#comment84824363_35893625) suggests.
Also, Rubocop needs to be >= 1.52.1 to work on Ruby 3.3 (out in < 2 weeks!) - see the PR [#11942](https://github.com/rubocop/rubocop/pull/11942) linked on the [release …
> add ignore_keys options, fixes #86

- .github/workflows/ci.yml
- README.md
This pull-request takes us automatically tests on ruby `2.7 .. 3.3`.
Tested on:
- Workflow runs on https://github.com/nishidayuya/hashdiff/actions/runs/8624323638
- Badge link checks on https://github.com/nishidayuya/hashdiff/blob/d092283595f3e6fe43c78265ddf14bfc9417c1ac/README.md (before 41e2723).
> Add GitHub actions workflow

- README.md
- changelog.md
- lib/hashdiff/compare_hashes.rb
- lib/hashdiff/diff.rb
- spec/hashdiff/diff_spec.rb
New README  examples too.
Also, FWIW my rubocop is suggesting enabling `AllCops` and using `rubocop-rake`
> fix #88 bug in ignore_keys option

- .github/workflows/ci.yml
This PR uses the `bundler-cache` feature of the Ruby-maintained Action `ruby/setup-ruby`.
[See `ruby/setup-ruby` parameters declaration](https://github.com/ruby/setup-ruby/blob/master/action.yml) for more information.
> CI: Use bundler-cache in ruby/setup-ruby

- README.md
- lib/hashdiff/compare_hashes.rb
- lib/hashdiff/diff.rb
- spec/hashdiff/diff_spec.rb
This is in response to issue #98, which requests an option to preserve the original key order of compared hashes. 
The existing implementation always outputs changes in a fixed order:
1. Deletions (-)
2. Updates (~)
3. Additions (+)
And within each group, keys are sorted alphabetically. 
Unfortunately, this means that simply disabling `sort_by` here isn’t enough: https://github.com/liufengyun/hashdiff/blob/b7734e3a29d6680b8371a7bc2c8fe149961b8abd/lib/hashdiff/compare_hashes.rb#L23-L25
because grouping by operation type still forces a reordering that doesn’t reflect the original hash structure. 
My goal for this option is to have all deletions and updates listed in the order they appear in the first hash. Then, similar to how Ruby’s Hash#merge appends new keys, any keys found only in the …
> Added :preserve_key_order option to maintain original hash key order
